### ISSUE TITLE
'Hold and quit' loses track of initial deal

### ISSUE THREAD

**Issue by RobertAJMarshall** [shlomif/PySolFC#209] opened 2021-05-01 19:24 UTC
If you play a deal and then 'hold and quit' and then restart pysol and restart the game you may not get the deal back that you started with. Doesn't always break but I've seen it frequently happen. Then when you restart you always get a different deal.

This is with the version of the code from github.

**Comment by joeraz** [comment] 2021-05-23 02:10
I've tried using Hold and Quit, and then Restart as you described several times with a number of different games, but thus far, I have not been able to reproduce this issue.

I'll keep trying on my end.  In the meantime, are there any specific games or situations under which this seems more likely to occur, or anything else that might help me reproduce the issue?  Thanks.

**Comment by RobertAJMarshall** [comment] 2021-05-23 18:35
I'm sorry there's a step missing in my description of how to replicate.
After restarting pysol, restart the game *twice* it's the second time that the different deal appears.
I can replicate this with spider and canfield (I'd not used canfield before but doubt if this makes any difference!). I think it always happens with this revised scenario.

**Comment by joeraz** [comment] 2021-05-23 19:59
With that, I was able to reproduce the issue.  Though I was also able to get it to reoccur a couple times without using Hold and Quit, just restarting the same game multiple times.  I'll look further and see what I can find.  Thanks.

**Comment by RobertAJMarshall** [comment] 2021-05-24 07:04
Great! I find that once it gets into that state it carries on producing different deals every time you 'redeal'

**Comment by joeraz** [comment] 2021-05-31 22:05
Okay.  I think I figured out what's happening here.  The problem is actually in the Load Game logic, so this will happen if you're loading a saved game in addition to using Hold and Quit.

When loading a saved game, PySol first attempts to read the game seed of the saved game, but if it fails, it would instead try to read the game state and set the random number generator with setState.  But it was checking that failure by verifying the random number generator against one type (random2.Random), when it's actually a different type (pysol_cards.random.MTRandom).  As such, it falsely believed loading the seed failed, and it was trying to load the random number generator using both methods.  They interfered with each other, ultimately leading to the reported bug.

To fix this, I just set it up to check if the random number generator was set or not, rather than trying to check against a specific type.  So far, this worked with my tests.

@RobertAJMarshall Here's a branch in my fork where my potential fix is in place - https://github.com/joeraz/PySolFC/tree/feature/fix-restart-bug.  If you get a chance, could you confirm if this fixes the issue for you?  Thanks.

**Comment by RobertAJMarshall** [comment] 2021-06-01 14:33
This looks good to me - thanks (prepares to see my %count of won games go down ;) )

**Comment by joeraz** [comment] 2021-06-02 00:09
The fix has been committed to master.  Closing now.

**Closed by joeraz** 2021-06-02 00:09 UTC
