### ISSUE TITLE
[2.10.1][win][andr] Not resizing to window dimensions to full extend

### ISSUE THREAD

**Issue by Fixer-007** [shlomif/PySolFC#262] opened 2022-07-03 16:43 UTC
I've noticed on windows and on android that Pysol is not resizing to actual windows size (by manual or auto-scaling)

Here is example, do note that I'm using older version on Windows 7, but Android version from f-droid clearly had this problem, despite enormous phone screens on android it looks miniscule and UI in general is ... weird (in light words).

I would like it to resize according to window size without those blank spaces (depending on game ofc), centering the game in the middle is also a good touch in my opinion.

![зображення](https://user-images.githubusercontent.com/16494741/177049120-84571c81-0644-45ec-83c4-aaac25b5c60f.png)

P.S. Thanks everyone for supporting development of this game!

**Comment by joeraz** [comment] 2022-07-03 19:37
You can enable Options/Card scaling/Auto Scaling, and the card sizes will automatically scale to the size of the window.  In version 2.15, this was made the default option, but it should be present in versions as old as 2.1.

In version 2.12, an option was added to automatically center the game to the screen.

**Comment by Fixer-007** [comment] 2022-07-04 14:27
Yes, but I have auto-scaling enabling, problem it does not want to scale it fully for some reason, at least in 2.10.1.

**Comment by joeraz** [comment] 2022-07-04 17:43
The "Preserve Aspect Ratio" option is enabled by default, so the cards will automatically fill the window either horizontally or vertically, but will not stretch or skew to fill the screen in both directions.  Most games have some space below them by design, in order to make sure there's enough room for longer stacks of cards.  A game that doesn't involve building in the tableau, like Fan or Pyramid, does not need this padding, so auto-scaling should match pretty closely in one direction.

However, older versions align the game to the top-left corner of the screen.  This was something I fixed with the "Center Layout" option added (and enabled by default) in version 2.12.  This option takes whatever excess space there is, and divides it evenly in both directions, so the game is in the center of the window.  Here's a screenshot showing this in version 2.16.

![Klondike216](https://user-images.githubusercontent.com/2691813/177199886-46b749ca-6b2b-4e01-be89-e736fca470fd.png)

**Comment by joeraz** [comment] 2022-07-07 00:21
Closing as this is a non-issue in the latest version.

**Closed by joeraz** 2022-07-07 00:21 UTC
