### ISSUE TITLE
Bug with table tiles

### ISSUE THREAD

**Issue by cardset** [shlomif/PySolFC#222] opened 2021-09-07 09:59 UTC
(Version 2.12. Windows)
If I enlarge the playing cards with ctrl +, 
the table tiles no longer fill the entire playing area. 

[https://i.imgur.com/DkALlEJ.jpeg](https://i.imgur.com/DkALlEJ.jpeg)

**Comment by joeraz** [comment] 2021-09-07 23:35
I've seen this happen before.  I think it's something to do with the way the table is created when the game is loaded, but thus far, I haven't been able to reliably reproduce the issue.  I'll take a closer look.

**Comment by joeraz** [comment] 2021-09-11 17:00
Okay, I think I have a fix in place for this one.

**Comment by joeraz** [comment] 2021-10-02 17:23
Closing since based on my testing, this has been resolved and included in the 2.14 release.  If this issue returns, feel free to reopen the ticket.

**Closed by joeraz** 2021-10-02 17:23 UTC
