### ISSUE TITLE
Broken Card Dealing in Spider (2 Suit)

### ISSUE THREAD

**Issue by mchieek** [shlomif/PySolFC#369] opened 2024-06-09 23:01 UTC
In the 2-Suit Spider game, the deal cards action (by pressing the new stack) is broken. The stack will show that there are still cards left to be dealt, but when it is pressed, no cards are dealt. Thus, the game can't be continued. This doesn't happen every time, but once every few games. Everything else looks the same and functions normally.

**Comment by joeraz** [comment] 2024-06-09 23:55
Can you confirm that there aren't any empty piles when you're trying to deal cards?

**Comment by mchieek** [comment] 2024-06-10 12:13
Hello,

There were empty piles when I tried to deal cards, because it was the end
of the game...

Thank you

**Comment by joeraz** [comment] 2024-06-10 21:32
Then this is not a bug.  As per the rules of Spider, you're not allowed to deal cards if there are empty piles.  You either have to split your remaining stacks to fill the empty piles or deal the next set of cards before making your last sequence to continue the game.

**Comment by joeraz** [comment] 2024-06-18 21:43
As this appears to be a non-issue, I'm closing this - if you can provide a save game file where you cannot redeal where there are no empty piles, I will reopen and investigate.

Though this isn't the first time someone reported this as an issue.  I'll make a note to add this to the FAQ page next time I update it.

**Closed by joeraz** 2024-06-18 21:43 UTC
