### ISSUE TITLE
No moves possible in Scorpion Tail

### ISSUE THREAD

**Issue by Arcorann** [shlomif/PySolFC#164] opened 2020-06-09 14:05 UTC
Tried to play Scorpion Tail, and I can't seem to make any moves. Not even the demo can make any moves. The only thing I can do is deal out the stock, but then after that I still can't make any moves.

This is on version 2.8.0 on Windows 10.

**Comment by shlomif** [comment] 2020-06-09 16:05
@Arcorann : hi! Thanks for the report. We shall try to reproduce, and investigate (using [bisection](https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md#what-does-bisecting-mean) / etc.) This is just an ack.

**Comment by shlomif** [comment] 2020-06-09 16:48
@Arcorann : hi! Please try the pysol build from https://ci.appveyor.com/project/shlomif/pysolfc/builds/33415917 and let us know of the verdict. Also please provide sample deal indices ("File → Select game by number").

**Comment by Arcorann** [comment] 2020-06-10 03:43
Tested again, still not working properly. It looks like it's not following the "move regardless of sequence" rule this time. Example is game number 93500419852916506624, where it should be possible to move either of the black 8s in the sixth column onto the red 9 on the left.

**Comment by shlomif** [comment] 2020-06-10 06:49
@Arcorann : thanks for checking! I'll try to investigate.

**Comment by cardset** [comment] 2020-06-10 08:31
The same issue in "Farmer's wife". It is not possible to take any card from the tableau.

**Comment by shlomif** [comment] 2020-06-10 09:24
@cardset, @Arcorann : here is what I discovered: 1. python2 pysol.py inside a py2 virtualenv appears to work fine. 2. python3 didn't work properly even in pysolfc-2.1.4 . 3. there are several "_isSequence" methods with two different signatures.

**Comment by shlomif** [comment] 2020-06-12 05:23
@cardset @Arcorann : hi! Please try again with https://ci.appveyor.com/project/shlomif/pysolfc/builds/33476542 after it completes to build. Thanks!

**Comment by shlomif** [comment] 2020-06-12 07:34
I added a test to https://github.com/shlomif/PySolFC/commit/11449de1b44c79a5171fecf5f27a05d5d2f66753 based on earlier tests for Scorpion_RowStack for a similar bug that was reported for it. It was also called by a multiple-inheritance issue.

**Comment by Arcorann** [comment] 2020-06-13 13:27
New build seems to work fine for me, thanks.

**Comment by shlomif** [comment] 2020-06-13 13:57
> New build seems to work fine for me, thanks.

You're welcome - thanks for trying that and letting me know

**Comment by cardset** [comment] 2020-06-14 04:42
![2dKon1Eq2M](https://user-images.githubusercontent.com/48878078/84584875-e8afde80-ae09-11ea-9642-135aabf0d3e6.gif)

Farmer's Wife:

Now i can take cards from the tableau, but


Can't move basecard from reserve to foundation
49820680964568883200

Can't move basecard from tableau to foundation
49820680964568883202


For all games:
I can't pause/unpause with keys (menu works)

**Comment by cardset** [comment] 2020-06-14 05:20
Sorry made a mistake, because the ingame help of the rules were not clear enough. 
Only complete piles go to the foundation.

But the bug still exists
12629171013173649408
The rule says "can move any face-up cards regardless of sequence".
So the red 10 on the last tableau, should go on the black jack on the eight tableau.

The same problem exists for Scorpions Tail.

**Comment by Arcorann** [comment] 2020-06-15 12:15
> Sorry made a mistake, because the ingame help of the rules were not clear enough.
> Only complete piles go to the foundation.
> 
> But the bug still exists
> 12629171013173649408
> The rule says "can move any face-up cards regardless of sequence".
> So the red 10 on the last tableau, should go on the black jack on the eight tableau.

This works for me in the build posted above, have you confirmed it with that build?

**Comment by cardset** [comment] 2020-06-15 20:52
Tried it again. The version with the number 1.0.614 works for me too.

**Comment by shlomif** [comment] 2020-06-16 07:31
> Tried it again. The version with the number 1.0.614 works for me too.

Thanks for checking. I'd like to merge the branch but there are other variants that may still suffer from the multiple inheritance regression.

**Comment by shlomif** [comment] 2020-06-22 10:11
Well, since I'm not too familiar with the other variants to determine if there are other regressions, I guess we can fix regressions as they are reported. Otherwise one can use a command such as `ack --sort '^class.*?,' pysollib/games` to look for potential problems. So closing this issue now to avoid clutter.

**Closed by shlomif** 2020-06-22 10:11 UTC
