### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by THEtomaso** [shlomif/PySolFC#110] opened 2019-04-09 16:53 UTC
I played a few games of 'Klodike by Threes' yesterday, and PySolFC froze with a "Not responding" message, while the music ended up in a .2 sec loop.
After terminating the process, and restarting PySolFC, I played for a short while, until the same thing occurred again.

No log.

* PySolFC build: v2.6.3
* OS version: Windows 8.1 Pro (x64)

--

**EDIT:**
Played for about 20 miunutes right now, and the freezing happened again!

**Comment by Programator2** [comment] 2019-04-09 20:58
I was able to reproduce the same issue. I'm still not sure what causes it. I'll investigate further.

**Comment by shlomif** [comment] 2019-04-10 08:14
On Tue, 09 Apr 2019 13:58:07 -0700
Roderik Ploszek <notifications@github.com> wrote:

> I was able to reproduce the same issue. I'm still not sure what causes it.
> I'll investigate further.
> 

Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Let’s talk about restores instead of backups - http://is.gd/WatQqu

Lone Starr: “Just what we need — a Druish princess.”
Barf: “Funny! She doesn’t look Druish.”
    — Spaceballs, http://www.imdb.com/title/tt0094012/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by Programator2** [comment] 2019-04-10 21:07
Well, it seems to be some deadlock between background music and sound effect (e.g. when moving card) playing. It occurs randomly, but only if a card was moved and sound effect played.

I tested on Python 3.4 with pygame 1.9.5, the problem was there (this is the version that is packaged with PySolFC v2.3.6). Interestingly, in the previous pygame version, 1.9.4, I was not able to reproduce the issue. It seems that some change in pygame (probably mixer) caused this.

I still can't pinpoint the exact location of the problem.

**Comment by Programator2** [comment] 2019-04-12 23:58
I have identified the problem. I'll be submitting a PR to pygame soon.

**Comment by Programator2** [comment] 2019-04-13 14:52
Here it is: https://github.com/pygame/pygame/pull/981

**Comment by THEtomaso** [comment] 2019-04-13 15:10
Great!
Hope shlomif has time to compile v2.6.4 soon. :)

**Comment by Programator2** [comment] 2019-05-02 14:12
v2.6.4 has been released containing fixed pygame. Closing.

**Closed by Programator2** 2019-05-02 14:12 UTC
