### ISSUE TITLE
A guide for creating custom cardsets.

### ISSUE THREAD

**Issue by Alucard648** [shlomif/PySolFC#46] opened 2017-08-26 00:54 UTC
Custom PySol cardsets outside the downloadable cardset pack are a rare thing in the Internet even in 2017. This is probably due to the fact that the config file specification is not well documented. Perhaps a guide for creating custom cardsets might solve this issue a bit.

**Comment by shlomif** [comment] 2017-08-26 10:48
Will you be willing to write one?

**Comment by Alucard648** [comment] 2017-08-27 01:20
If I would know specifications of config file which is inside each cardset folder...

**Comment by jan-kleks** [comment] 2017-08-27 13:11
Wouldn't the file specification change after adding [SVG support](https://github.com/shlomif/PySolFC/issues/3)? 

Another problem with the current cardsets (and other graphical elements) is that they're of an extremely low resolution, and some are designed poorly as well... My favorite PySol's cardsets are the default one and Oxymoron. They have a nice retro feel, and look good, even though they're pixelated.

**Comment by shlomif** [comment] 2017-08-27 17:59
On Sun, 27 Aug 2017 06:11:33 -0700
Jan Kleks <notifications@github.com> wrote:

> Wouldn't the file specification change after adding [SVG
> support](https://github.com/shlomif/PySolFC/issues/3)? 
> 

Maybe, maybe not. Hopefully backward compatibility will be retained.

> Another problem with the current cardsets (and other graphical elements) is
> that they're of an extremely low resolution, and some are designed poorly as
> well... My favorite PySol's cardsets are the default one and Oxymoron. They
> have a nice retro feel, and look good, even though they're pixelated. 
> 



--

**Comment by shlomif** [comment] 2017-10-04 19:06
Adding the hacktoberfest label. Contributors are welcome.

**Comment by Alucard648** [comment] 2018-05-20 10:50
#83

**Comment by cardset** [comment] 2019-03-24 08:43
> Perhaps a guide for creating custom cardsets might solve this issue a bit.

kdwayne described here how to do nice cardsets:
https://sourceforge.net/p/pysolfc/discussion/503708/thread/6dc85931/?limit=25
In short: use cardsetmaker, set size of cards, make a fake set with any pics, exchange the files in the cardset folder with nice cards.

**Comment by cardset** [comment] 2020-03-21 10:51
To make things easy you could also use the most recent version of
Cardset Maker 0.5 for PysolfFC

[https://sourceforge.net/p/pysolfc/discussion/503708/thread/68fc17a6f5/?limit=25](url)

Here are some cardsets:
http://www.andsa.de/en/pysol.html

**Comment by ShimmerFairy** [comment] 2020-09-21 20:50
Some questions are still left unanswered:

1. Where do I install cardsets I download? (And I hope the answer isn't "just install it in `/usr/share/...`".)
2. Where is the source code for Cardset Maker, so it can be used on non-Windows computers?

**Comment by cardset** [comment] 2020-09-23 18:06
1. For me it is 
.../PySol Fan Club edition/data/
Put the whole drawer of the new created cardset there

2. The last published source was version 0.2. (Never tested on linux or mac.)
But this version makes only sense for cards witch have already ranks and suites on it.

[Cardset-Maker-0.2_source.zip](https://github.com/shlomif/PySolFC/files/5270083/Cardset-Maker-0.2_source.zip)

**Comment by shlomif** [comment] 2020-09-24 06:16
Thanks for sharing @cardset ! The comment at the top of the `.py` file in the zip says it is [GPLv2+](https://spdx.org/licenses/GPL-2.0-or-later.html). It has quite a few flake8 warnings though. @ShimmerFairy : I think you can put cardsets under `~/.PySolFC/cardsets/`

**Comment by Neelix57** [comment] 2020-09-29 14:11
I made a tutorial to create cardsets manually. I found this was missing, because Cardset Maker doesn't give the opportunity to fully custom cardsets.

But some questions remain. For the variables I use to identify the various settings, see the attached file.

>- $A: andsa said [here](https://sourceforge.net/p/pysolfc/discussion/503708/thread/6dc85931/#ee53) this corresponds to:
> French Sets=4 Mahjong=5 or 6, but what is this exactly ?

>- Which types could exactly be used ?

>- Could the number of cards be different than 42, 48, 52, 68, 78, 96 or 120 ?

> - Cardset location ([as said here](https://sourceforge.net/p/pysolfc/discussion/503708/thread/6dc85931/#ee53)) mostly begin with a number (e.g. 12362-wilhelmtell). Is it really the location of cardsets ? Mine are in ~/.PySolFC/cardsets and it works  fine.

Feel free to improve or modify my tutorial. All comments are welcome.

[cardsets_tutorial.txt](https://github.com/shlomif/PySolFC/files/5299564/cardsets_tutorial.txt)

**Comment by shlomif** [comment] 2020-09-29 17:45
> I made a tutorial to create cardsets manually. I found this was missing, because Cardset Maker doesn't give the opportunity to fully custom cardsets.
> 
> But some questions remain. For the variables I use to identify the various settings, see the attached file.
> 
> > * $A: andsa said [here](https://sourceforge.net/p/pysolfc/discussion/503708/thread/6dc85931/#ee53) this corresponds to:
> >   French Sets=4 Mahjong=5 or 6, but what is this exactly ?
> 
> > * Which types could exactly be used ?
> 
> > * Could the number of cards be different than 42, 48, 52, 68, 78, 96 or 120 ?
> 
> > * Cardset location ([as said here](https://sourceforge.net/p/pysolfc/discussion/503708/thread/6dc85931/#ee53)) mostly begin with a number (e.g. 12362-wilhelmtell). Is it really the location of cardsets ? Mine are in ~/.PySolFC/cardsets and it works  fine.
> 
> Feel free to improve or modify my tutorial. All comments are welcome.
> 
> [cardsets_tutorial.txt](https://github.com/shlomif/PySolFC/files/5299564/cardsets_tutorial.txt)

Thanks @Neelix57 ! Which licence is it under: https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md#i-want-to-release-my-code---which-open-source-licence-should-i-use ?

**Comment by cardset** [comment] 2020-09-29 19:16
> 
> 
> because Cardset Maker doesn't give the opportunity to fully custom cardsets.
> 

What is missing?  (Except that it only supports poker sets)

> > * Cardset location ([as said here](https://sourceforge.net/p/pysolfc/discussion/503708/thread/6dc85931/#ee53)) mostly begin with a number (e.g. 12362-wilhelmtell). Is it really the location of cardsets ? 

I think the prefix (1234...) is only to differ from cardsets with the same name.
Nowadays i think, it is not the location. It is to give the cardset a name that makes no problems with loading/calling. For example: changing capital letters to lowercase, and filling the spaces with "-"

andsa / cardset 
(sorry, could not get the same name on both pages)

**Comment by Neelix57** [comment] 2020-09-30 07:04
@shlomif : All my work is under GNU General Public Licence

**Comment by shlomif** [comment] 2020-09-30 07:19
> @shlomif : All my work is under GNU General Public Licence

Thanks for the reply! Note that it has to be [GPLv3-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html) or [gplv2-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html) for it to be usable by PySolFC. Please clarify that this is the case.

**Comment by Neelix57** [comment] 2020-09-30 07:31
@cardset : 

> What is missing? (Except that it only supports poker sets)

The bottom images have always scare corners. I worked out with round corners cards and try to set the "Round Corners" settings for cards and backs higher but it does nothing. It works only for the cards.
The other thing is the ability to customize the offsets and shadows of the cards and to give card manager's categories, because for beginner it's not too simple to work in the config file.

> in "app.py" it seems that this vari belongs to the existing number of fields in first line. (your: $FTM;$B;$C;$D;$E;$F)

Yes, you're right. Thank you for the hint.

**Comment by Neelix57** [comment] 2020-09-30 07:34
@shlomif : GPLv3 or later

**Comment by shlomif** [comment] 2020-09-30 07:44
> @shlomif : GPLv3 or later

Thanks for the clarification, @Neelix57 !

**Comment by cardset** [comment] 2020-09-30 11:16
> round corners

Do you speak about this bug?
https://sourceforge.net/p/pysolfc/discussion/503708/thread/68fc17a6f5/95ae/attachment/bug-border.jpg
it is solved

>  The other thing is the ability to customize the offsets and shadows of the cards and to give card manager's categories

Okay, i could add these futures. But from my point of view, beginners don't even know about offsets or categories. This is for somewhat experienced users. I try to find a solution that satisfy both of us. (Maybe an hopefully easy GUI for beginners and a menu for specialised things)
 

Even if you don't use the tool, if you (or somebody else) have ideas, or wishes please write your opinion in this thread. 
https://sourceforge.net/p/pysolfc/discussion/503708/thread/68fc17a6f5/

**Comment by Neelix57** [comment] 2020-09-30 12:29
Here is a screenshot of PySolFC:
![screenshot png](https://user-images.githubusercontent.com/63342144/94683500-f04ab300-0326-11eb-9e72-fa5409b689b6.gif)
As you can see, the cards have round corners, but the bottoms have square corners.

Here is something new, the corners doesn't appear correctly. It's the first time.

For test purposes, I used the existing "Paris" cardset in the pysolfc-cardsets-2.0 package.

I work with Cardset Maker 0.65 in Wine, under Xubuntu Bionic. In Cardset Maker the corners appears round but incorrect as in PySol. In facts, the cards are written in the output folder as they appears in Cardset Maker.

**Comment by cardset** [comment] 2020-09-30 16:57
Okay, now i understand.

I never touched the bottom cards, because...
 - 1. i think layout of desk is a matter of the game itself.
 - 2. i never got problems with it.
 Screenshot: https://i.imgur.com/HtuT8sP.png
 
 As a first test, i removed all bottom cards from my cardset, and the game still works.
 Then i was looking around and found corresponding graphics in "../PysolFC/data/images/cards/bottoms/"
 It seems they changed loading of bottom cards to this place.
 
 Probably solution for you: Updating the game or sending an issue report. If this does not work, making the edges round in GIMP.
 
 Solution for me: Rounding the corners of the bottoms for older versions of the game.

**Comment by cardset** [comment] 2020-09-30 16:57
Thank you for the information, that Cardset Maker works with Wine and Linux.This is for sure useful for other users.

**Comment by Neelix57** [comment] 2020-09-30 19:51
> Then i was looking around and found corresponding graphics

Great! So many years playing PySolFC and I never found out these images, I thought the bottoms was only defined by the ones in the cardsets folders. Thanks Man.

> Probably solution for you: Updating the game or sending an issue report

I don't think that were a bug. These bottoms should be default ones for cardsets created without bottoms.

**Comment by cardset** [comment] 2020-10-01 04:46
> I don't think that were a bug. These bottoms should be default ones for cardsets created without bottoms.

But i get them even if i have ugly bottoms in the cardsets. Should be the same for you.

**Comment by Neelix57** [comment] 2020-10-01 09:04
I take a closer look this morning. The images are squared. Nothing to do, I must use Gimp.

**Comment by cardset** [comment] 2020-10-01 16:51
> 
> 
> I take a closer look this morning. The images are squared. Nothing to do, I must use Gimp.

Just to make things clear. Is the Paris cardset made with Cardset Maker the only one which has squared  corners?

I made a test. The game creates the corners like the shape of card 01c.png.
Screenshot: https://i.imgur.com/y2DYTRo.png

**Comment by Neelix57** [comment] 2020-10-01 19:12
No, all cardsets have square corniers.
Could it be a bug with Cardset Maker running under Wine ?

**Comment by rexx790** [comment] 2020-10-02 01:18
I had similar issues on a fresh install of Ubuntu Mate 20.04. 
This is what i did to remedy the problems. Uninstalled Pysolfc. I then installed Pysolfc using synaptic package manager. I didn't install the extra cardsets. Before i opened Pysolfc for the first time, i deleted the original cardset and replaced with one of my own. This worked perfectly, and i have added over 300 cardsets without any further issues. Another issue i had was Pysolfc would no longer recognize .jpg for table tile.(backgrounds) Using only .png files was the work around.

**Comment by cardset** [comment] 2020-10-02 05:53
> 
> 
> No, all cardsets have square corniers.
> Could it be a bug with Cardset Maker running under Wine ?

If all cardsets, have square corners, it has nothing to do with Cardset Maker.
Because the older cardsets are created with something other.

**Comment by cardset** [comment] 2020-10-02 18:58
To my posting this morning.
Of course delivers Cardset Maker wrong bottoms, i wrote this some days ago.
(Not a bug, i just did not know that they are needed).
The question is, are they still necessary? 
Or better we let PySol create the bottoms itself.

For testing, could you remove all the bottoms from your Paris cardset (Pysol closed),
And start the game afterwards with the set?
(if things work good, you get round corners and red hearts and diamonds)
Maybe your the one who gets the correct but bad bottoms,
and we fail loading and get the new ones from Pysol.

**Comment by Neelix57** [comment] 2020-10-03 07:19
I tried it and couldn't get round corners. Because my PySolFC installation is something unconventional, I tried with PySolFC without installation, the issue was gone. So, I tried install PySolFC the conventional way (in Python environment), it also works.

Thank @cardset, @rexx790

**Comment by cardset** [comment] 2020-10-03 10:17
I came to the same conclusion.
Your game did not find the correct path.


Made some additional tests:
First it loads from "GAME/data/images/cards/.."
If i remove this drawer, it loads the bottoms from the custom cardset. 
If i remove both, the game creates only a squared shape.

Screenshot:
https://i.imgur.com/LU6Xk0i.png

**Comment by rexx790** [comment] 2020-10-06 03:52
[
![Example](https://user-images.githubusercontent.com/39487652/95156108-71032680-07e1-11eb-8f74-042a33e7e1e4.jpg)
](url)
It's great that the config file is getting some documentation.
I have a query about  "*$A:* The number of fields in first line". As The screenshots show, the picture on the left had its value in the config file altered from 6 to 4 to match the documentation. The result was that it places the tiles further apart. 
Maybe the "$A" value represents something else.

**Comment by cardset** [comment] 2020-10-06 08:00
Sorry, another try:
It is cardset version number (cs.version) that belongs to the number of fields divided through ";"

Version 3:
Name; Version; gfxFormat; Type; Number of cards

Version 4:
Name; Version; gfxFormat; Type; Number of cards; Styles

Version 5:
Name; Version; gfxFormat; Type; Number of cards; Styles(+Country); Year

Version 6:
Name; Version; gfxFormat; Type; Number of cards; Styles(+Country); Year


Majongg differs in version 6.
It uses another way fox xOffset, yOffset, and the shadow offsets.
Please test with the original gnome-mahjongg-1


I think this will cause issues in the future,
because a mahjongg set that has no Year Field, can't use the modern layout.
Please test with the original ivory-mahjongg


Source:
https://github.com/shlomif/PySolFC/blob/master/pysollib/games/mahjongg/mahjongg.py

**Comment by Neelix57** [comment] 2020-10-06 09:29
I confirm. I made some tests with my custom tilesets and with Ivory Mahjongg. $A must always be set to 6 and the year must be set. The year could also be defined to 0 at your convenience.
I will fix this in the tutorial.

Please feel free to report any other issue.

**Comment by jnumm** [comment] 2020-10-06 12:01
Hi guys, I'm going to move the parsing code in a module of its own (PR #183) to make it easier to experiment with the format. Would you find that helpful?

**Comment by rexx790** [comment] 2020-10-06 12:10
Thanks, cardset,Neelix for clarifying.
My mahjong tilesets have always worked fine in linux, but failed to show up in windows. Using your explanation i have been able to rectify this.

**Comment by cardset** [comment] 2020-10-08 16:29
> 
> 
> I will fix this in the tutorial.
> 
> Please feel free to report any other issue.

Please remove or edit your "cardsets_tutorial.txt" in this thread.
It is now outdated. So it can be confusing
https://github.com/shlomif/PySolFC/issues/46#issuecomment-700732159

Or replace it with this link:
https://github.com/shlomif/PySolFC/blob/master/contrib/customize_cardset.asciidoc

Description of "$A" is still inaccurate.

**Comment by joeraz** [comment] 2022-12-02 00:14
Don't know if anyone's still monitoring this, but I was wondering what the status of this document is, and if there's still specific things that need to be done with it, or if this ticket can be closed?  It was quite helpful for me when I was adding the hi-res cardsets for the 2.15 release.

I personally think it would be a good idea to convert it to HTML and add it to the main documentation - that way, it'll be easier for more casual users to find it.

**Comment by shlomif** [comment] 2022-12-02 11:50
On Thu, 01 Dec 2022 16:14:57 -0800
"Joe R." ***@***.***> wrote:

> Don't know if anyone's still monitoring this, but I was wondering what the
> status of this document is, and if there's still specific things that need to
> be done with it, or if this ticket can be closed?  It was quite helpful for
> me when I was adding the hi-res cardsets for the 2.15 release.
> 
> I personally think it would be a good idea to convert it to HTML and add it
> to the main documentation - that way, it'll be easier for more casual users
> to find it.
> 

:+1:

-- 

Shlomi Fish       https://www.shlomifish.org/
NSA Factoids - https://www.shlomifish.org/humour/bits/facts/NSA/

Faith: Hey! “Slut” is such a 90s term. The new name for that is “polyamorous”!
    — https://www.shlomifish.org/humour/Buffy/A-Few-Good-Slayers/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment] 2023-01-14 01:40
Okay, since I haven't heard any objections, I'll convert the guide to HTML and add it to the main documentation, then I'll close this ticket after.

**Comment by shlomif** [comment] 2023-01-14 05:22
On Fri, 13 Jan 2023 17:40:42 -0800
"Joe R." ***@***.***> wrote:

> Okay, since I haven't heard any objections, I'll convert the guide to HTML
> and add it to the main documentation, then I'll close this ticket after.
> 

+1 . thanks.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Summer-Glau/

There are at least 137 Larry Walls in the U.S., but only one that matters.
    — https://www.shlomifish.org/humour/bits/facts/Larry-Wall/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment] 2023-01-14 19:17
All updated.  The new file is at https://github.com/shlomif/PySolFC/blob/master/html-src/cardset_customization.html - please make sure any future changes to this doc are reflected in this file.

Closing the ticket.

**Closed by joeraz** 2023-01-14 19:17 UTC
Labels: enhancement, Hacktoberfest
