### ISSUE TITLE
[bug] Solitaire wizard won't save custom games

### ISSUE THREAD

**Issue by Neelix57** [shlomif/PySolFC#177] opened 2020-09-27 12:49 UTC
Here is a screenshot of the error:
![screenshot](https://user-images.githubusercontent.com/63342144/94365314-10346980-00d0-11eb-8c89-7f5f598d94c7.jpg)

- Step to reproduce:
- Go to Solitaire Assistant
- Define your game parameters
- Click Ok

Version 2.10.1 of PySolFC installed from source
OS: Xubuntu 18.04 64bits

**Comment by Butterfly** [comment] 2020-09-27 15:10
BINGO! I reproduced! This is a completely different comment from what I started out with.. I'm in Debian Linux, by the way.

1\) Mine's open via terminal in hopes an error might kick out there, too. That actually worked. This is what I received a few times:

```
PySolFC: WARNING: b'error loading plugin /home/candycane/.pysolfc/plugins/customgame4.py: invalid syntax (customgame4.py, line 10)'
PySolFC: WARNING: b'error loading plugin /home/candycane/.pysolfc/plugins/customgame5.py: invalid syntax (customgame5.py, line 10)'
```

2\) I wasn't initially able to reproduce. I would click "Solitaire Wizard" under "Edit". I changed 4 to 5 on "Reserves" tab then clicked "OK". It kicked me OUT of Mahjongg and INTO Freecell with *NO* error. That "reserves" option turned out to be that you have 5 free spots open on the left top. The deepest relevancy is that an option was successfully changed. "Sad face" that I got kicked out of the game I was trying to play. :smile: 

Next, I went back into Mahjongg and messed around with a "few" things, There continued to be no errors. THEN.. I went back in one last time before posting. On the default "General" tab, I changed the name then clicked OK. That's when I received the exact error message as is in your image here.

When I go back into the Wizard without exiting Mahjongg, the name is not changed. When I try to change it again, I again successfully reproduce this thread's error.

3\) Updating this to now add: I closed Pysolfc and reopened it via terminal. It now spews out the above terminal line error that has evolved to include: `customgame7.py`, `customgame8.py`, and `customgame9.py`. Yes, it skipped "6".

4\) Getting kicked out of Mahjongg Traditional Reviewd and into Freecell had a useful side benefit. For Freecell, I noticed that the "Edit current game" option is live under Edit. That same option is grayed out for Mahjongg. I don't know if that matters in any way, but it seems to be an on-topic difference worth noting.

Hope this helps... somehow!

**Comment by Neelix57** [comment] 2020-09-27 18:12
I launched the game from command line. The same errors occurs, one for each custom game. According the line of the error, it seemed that the game's name is misspelled on that line. It looks like this :
`'name': 'b'test''`

I closed PySolFC and modified the line as this:
`'name':'test'`

and relaunched PySolFC. The error was gone for that custom game. I could play, but, trying to edit my custom game, got the same error, and the same line in the custom game file was changed to it's initial state, causing the error again.

Despite the error, creating or editing the custom game, its parameters seems to be added to the file.
Changing the line as mentioned above seems to be a good workaround for now. Hope this could be fix in a future version.

**Comment by shlomif** [comment] 2020-09-28 07:00
@Neelix57 @Butterfly : thanks for the report and the info! Please try it in this branch: https://github.com/shlomif/PySolFC/tree/try-to-fix-github-issue-177

**Comment by Neelix57** [comment] 2020-09-28 13:52
Great ! It works fine for me.

**Comment by Neelix57** [comment] 2020-09-28 15:06
I passed something. It work great but only with the default names. Giving my custom game a custom name, the error occurs again.

**Comment by Anomalocaridid** [comment] 2021-05-17 03:31
This exact same bug is still present.

**Comment by joeraz** [comment] 2021-05-23 02:19
I was able to reproduce this error as well - it looks like the branch with the fix was not yet merged.

@shlomif - Is it okay if I test and clean up that branch and merge the fix?  Or is there some other reason that has not been merged yet?  Thanks.

**Comment by shlomif** [comment] 2021-05-23 04:33
> I was able to reproduce this error as well - it looks like the branch with the fix was not yet merged.
> 
> @shlomif - Is it okay if I test and clean up that branch and merge the fix? Or is there some other reason that has not been merged yet? Thanks.

Go for it!

**Comment by joeraz** [comment] 2021-05-23 19:58
The fix has been merged in now.  Closing this issue.

Corrupted games that were created as a result of this bug will still need to be deleted manually to fully fix your local copies.  If this issue occurs on any new games, please reopen and I'll take a closer look.  Thanks.

**Closed by joeraz** 2021-05-23 19:58 UTC
Labels: bug
