### ISSUE TITLE
Game  Issue

### ISSUE THREAD

**Issue by junkthing-123** [shlomif/PySolFC#378] opened 2024-08-28 20:32 UTC
![PySol](https://github.com/user-attachments/assets/2bb2c704-dce3-4f29-8073-d324560b474f)
First time submittal.
Like the games.  Problem with the Batsford game I played is not my PC.  Picture attached displays the presence of the issue.  It seems only one of the two 'Three of Clubs' is not available, - impossible to win the game.

**Comment by joeraz** [comment] 2024-08-29 00:01
So the other three of clubs never showed up at any point during the game?

Do you know the number of this game, or have a save game file where the issue has occurred?

**Comment by junkthing-123** [comment] 2024-08-30 03:43
Just got to your message.
No to both your questions.
I stopped playing the game when the auto play option I choice
and I noticed there was no three of club card to proceed.

Before doing this response, I looked at the photo I sent again.
Unless my vision is off, I have since your email gone through the
cards in the picture which have all been played showing face up
 and it would seem that more than the second three of clubs is
missing.

Counting all cards in the lower portion of the video as shown face
up as well the cards determining/counting cards in the upper lay-down,
by my calculations there are a total of 12 cards missing.

All of the above stated, and your indication that the issue I found may
be a single game issue and not the entire game file, I will continue to
play the game and others.  If, I run across another situation of missing
card(s) in a game - I will let you know.
________________________________

**Comment by joeraz** [comment] 2024-08-31 01:56
Are you sure?  I just counted the cards there (foundations, tableau rows, and waste), and see 104 cards total, as I'd expect.

From just the screenshot, I'd think the missing cards are most likely in the waste pile.  I played a few games, and was not able to reproduce this issue.  If it happens again, with another deal, if you can provide me the game number or a save game file, I can investigate off that.

**Comment by junkthing-123** [comment] 2024-08-31 18:26
Based on your comments - my oversight, sorry.  Too eager to win and had
taken some medication from recent operation before playing the game.
Thanks for the trouble and comments back.  Now back to this and other
games from the site remarking with more caution.
________________________________

**Comment by joeraz** [comment] 2024-08-31 20:00
Okay.  I'll close this then.

**Closed by joeraz** 2024-08-31 20:00 UTC
